### ISSUE TITLE
address security vulnerabilities alert

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/pass-java-client#106]
as mentioned here: https://github.com/OA-PASS/java-fedora-client/network/alert/pom.xml/com.fasterxml.jackson.core:jackson-databind/open

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete.  This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
