### ISSUE TITLE
Throw exception when using default limit and all index records are not returned

### ISSUE THREAD

**Issue by karenhanson** [eclipse-pass/pass-java-client#13]
The default limit for the fedora-java-client's `findAllByAttribute[s]` is currently 3000. If the client app is using the default limit and there are more than 3000 records, unless the client app specifically checks, there si no indication that you do not have the full set of results.  An exception should be thrown in this case to signal to the client that there was a problem.

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete.  This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
